# Generated by Django 4.1.7 on 2023-03-23 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='emp',
            name='username',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
